### ISSUE TITLE
Warum wird das Chat-Paket in mehrere Nachrichten aufgeteilt?

### ISSUE THREAD

**Issue by marek22k** [lgc-4/ProgProjekt-Netzwerkstandard#12]
Hallo,

warum wird eine Chat-Nachricht (bei mehr als 256 Zeichen) in mehrere Nachrichten aufgeteilt? Da Protokoll, welches wir verwenden (TCP), sollte doch eigentlich dazu fähig sein eigenständig Pakete aufzuteilen.
Und selbst wenn wir die Pakete selber aufteilen wollen, würde eine Größe von 1200 Bytes oder ähnliches meiner Meinung nach sinnhafter sein. 1280 ist das Minimum MTU für IPv6. Wenn wir nun 60 Bytes für TCP nehmen, 40 Bytes für IPv6, 7 Bytes für "SHOOT" erhalten wir noch 1173 Bytes für die eigentliche Chat-Nachricht. Wenn man nun von Unicode mit jeweils zwei Bytes pro Zeichen ausgeht, könnten wir über 500 Zeichen pro Paket versenden.

Übersehe ich hier etwas?

**Comment by lgc-4** [comment]
Nach Protokoll **können** längere Nachrichten in mehrere Pakete aufgeteilt werden. Einfach die Länge des Eingabefeldes auf 256 Zeichen zu limitieren wäre ebenso legitim.

Ich glaube unser ursprünglicher Gedankengang war Chat Nachrichten in der Länge so streng zu limitieren, um das Layout in der GUI und generell die Implementierung zu erleichtern, in dem die Nachrichten eine vorhersehbare Maximallänge haben.

Schlussendlich denke ich es sollte auf jeden Fall irgendeine Maximallänge existieren. 256 war einfach so eine hübsche Zahl :)

Ich wäre grundsätzlich nicht davon abgeneigt diese Limitierung anzupassen.

**Comment by marek22k** [comment]
Danke für die Antwort. Das "können" habe ich übersehen.
