### ISSUE TITLE
WITHDRAW Paket führt nicht zum Sieg des verbleibenden Spielers

### ISSUE THREAD

**Issue by palait** [lgc-4/ProgProjekt-Netzwerkstandard#9]
Das `WITHDRAW`-Paket führt in der aktuellen Version des Protokolls zum Sieg des Spielers, der das Spiel nicht vorzeitig abgebrochen hat. Dies würde es ermöglichen, dass sich zwei Spieler absprechen, jeweils ein Spiel starten und direkt nach dem Spielstart vorzeitig abbrechen. Dies würde einen schnellen, unfairen Aufstieg beider Spieler in das höchste Semester ermöglichen, ohne eine wirkliche Spielleistung erbracht zu haben. Zudem könnte dies für lokale Implementationen von Items, Punkteständen, etc. mancher Gruppen zu einem unfairen Spielerlebnis führen.
### Vorschlag:
Das `WITHDRAW`-Paket führt nicht zum Sieg des "noch stehenden" Spielers, sondern bei beiden Spielern zu einer Niederlage, bzw. einem Unentschieden.

**Comment by lgc-4** [comment]
Den schnellen und unfairen Aufstieg durch die Absprache zwischen Spielern kann man ohnehin nicht effektiv unterbinden. Die Spieler könnten sich auch einfach austauschen, wo sie ihre Schiffe platziert haben und so in einer ähnlich hohen Geschwindigkeit aufsteigen.

Deinen Punkt mit "Items und Punkteständen" müsstest du etwas genauer erläutern, da bin ich mir nicht ganz sicher was du damit meinst, und wie es das Spielerlebnis unfair machen würde.

Beim Aufgeben beide Spieler verlieren zu lassen oder ein Unentschieden festzustellen wäre enorm unfair. Sollte ein Spieler am gewinnen sein und nurnoch einen Schuss benötigen um den Sieg zu erlangen, könnte der Gegner einfach "aufgeben" und der Spieler der eigentlich hätte gewinnen sollen hat nun verloren oder nur unentschieden gespielt. Da ist mir persönlich die aktuelle Version deutlich lieber.

Ein seperates Paket um ein Unentschieden anzubieten bzw. anzunehmen, ähnlich wie beim Schach, könnte jedoch eine hilfreiche Funktion sein.
